### ISSUE TITLE
Setting web_context_url and administration_url to load balancer url while federating

### ISSUE THREAD

**Issue by anandak** [Esri/arcgis-cookbook#290] opened 2021-06-14 10:01 UTC
Hi @cameronkroeker, we have successfully done a multi machine base enterprise deployment of 10.8.1 in Amazon cloud. All machines are in HA, i.e., web adaptor, portal, server and data store. This is fronted by the Amazon's load balancer which we are using as the web_context_url. 
However we see that during federation, the `web_context_url` is used only for the `services URL` while the `administration URL` is set to the `private_url (6443)` thats defined in the role JSON file. According to ArcGIS help docs, it seems that when in HA, you should use the load balancer URL for the `administration URL` too.

Here is a snip from help docs:
![image](https://user-images.githubusercontent.com/1454027/121874099-abd03d80-cd24-11eb-9686-f1b47f7678c4.png)

In the role JSON we have to specify the `private_url` which uses the 6443 port and `web_context_url`, which is the load balancer URL. How can we accomplish the above configuration using the role JSON file? Is this the recommended way to federate when using HA?

**Comment by cameronkroeker** [comment] 2021-06-14 15:26
closing as a duplicate of:

https://github.com/Esri/arcgis-cookbook/issues/289

**Closed by cameronkroeker** 2021-06-14 15:26 UTC
Labels: duplicate
