### ISSUE TITLE
Installation of Portal fails within Recipe 'portal.rb'

### ISSUE THREAD

**Issue by mu88** [Esri/arcgis-cookbook#58] opened 2017-02-01 15:56 UTC
Hello,

I'm trying to install ArcGIS Server + Portal 10.4.1 with your Chef Cookbook.

Within the recipe 'portal.rb', the installation fails with "ArgumentError: File 'D:\Programs\ArcGIS\Portal/framework/runtime/ds/framework/etc/hostidentifier.properties' does not exist".

I've checked the file system, the directory "D:\Programs\ArcGIS\Portal/framework/runtime/ds" doesn't exist.
Any ideas how to resolve this?

Regards
mu88

**Comment by pbobov** [comment] 2017-02-01 17:40
This happens because of a bug in arcgis-server cookbook.  10.4.1 backward compatibility was broken by 10.5 specific changes in portal.rb provider. 

I fixed the problem in branch issue58. Please try cookbooks from that branch (https://github.com/Esri/arcgis-cookbook/tree/issue58). (See pull request https://github.com/Esri/arcgis-cookbook/pull/59 for details of the fix.) 

The issue will be resolved in the next release of ArcGIS Chef cookbooks.

**Comment by mu88** [comment] 2017-02-02 08:47
That did the trick, thank you very much!

**Comment by pbobov** [comment] 2017-03-03 23:53
The issue is fixed in arcgis-enterprise cookbook v3.0.0.

**Closed by pbobov** 2017-03-03 23:53 UTC
